import { Product } from "./types";

// Fortune Series Bathroom Accessories - Chrome Finish
export const fortuneSeriesProducts: Product[] = [
  {
    id: "fortune-ft-109",
    name: "Towel Rack",
    slug: "fortune-ft-109",
    category: "fortune-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 10980,
    code: "FT-109",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/1.jpg",
    description: "Fortune Series Towel Rack with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-107",
    name: "Roll Holder With Mobile Stand",
    slug: "fortune-ft-107",
    category: "fortune-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 4320,
    code: "FT-107",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/5.jpg",
    description: "Fortune Series Roll Holder with Mobile Stand - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Mobile Stand", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-110",
    name: "Towel Rack With Shelf",
    slug: "fortune-ft-110",
    category: "fortune-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 13500,
    code: "FT-110",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/43.jpg",
    description: "Fortune Series Towel Rack with Shelf - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Shelf", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-105",
    name: "Tumbler Holder",
    slug: "fortune-ft-105",
    category: "fortune-series",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 3250,
    code: "FT-105",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/46.jpg",
    description: "Fortune Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-102",
    name: "Napkin Holder",
    slug: "fortune-ft-102",
    category: "fortune-series",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 4320,
    code: "FT-102",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/44.jpg",
    description: "Fortune Series Napkin Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-103",
    name: "Towel Bar 600mm",
    slug: "fortune-ft-103",
    category: "fortune-series",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 7650,
    code: "FT-103",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/45.jpg",
    description: "Fortune Series Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-101",
    name: "Soap Holder",
    slug: "fortune-ft-101",
    category: "fortune-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 3150,
    code: "FT-101",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/14.jpg",
    description: "Fortune Series Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-104",
    name: "Liquid Dispenser",
    slug: "fortune-ft-104",
    category: "fortune-series",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 4770,
    code: "FT-104",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/47.jpg",
    description: "Fortune Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-108",
    name: "Tumbler + Liquid + Napkin Ring Holder 600mm",
    slug: "fortune-ft-108",
    category: "fortune-series",
    subcategory: "combination-holder",
    finish: "Chrome",
    price: 10170,
    code: "FT-108",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/48.jpg",
    description: "Fortune Series Combination Holder (Tumbler + Liquid + Napkin Ring) - Chrome Finish - 600mm",
    material: "Brass + Glass",
    features: ["600mm Length", "3-in-1 Holder", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-106",
    name: "Paper Holder",
    slug: "fortune-ft-106",
    category: "fortune-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 2880,
    code: "FT-106",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/49.jpg",
    description: "Fortune Series Paper Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "fortune-ft-tumbler-liquid",
    name: "Tumbler + Liquid Dispenser",
    slug: "fortune-ft-tumbler-liquid",
    category: "fortune-series",
    subcategory: "combination-holder",
    finish: "Chrome",
    price: 6030,
    code: "FT-TL",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/50.jpg",
    description: "Fortune Series Tumbler + Liquid Dispenser Combination - Chrome Finish",
    material: "Brass + Glass",
    features: ["2-in-1 Holder", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
];
