import { Product } from "./types";

// Pyramid Series Bathroom Accessories - Chrome Finish
export const pyramidSeriesProducts: Product[] = [
  {
    id: "pyramid-pr-104",
    name: "Glass Soap Dish",
    slug: "pyramid-pr-104",
    category: "pyramid-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1530,
    code: "PR-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/22.jpg",
    description: "Pyramid Series Glass Soap Dish with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Dish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-106",
    name: "Tumbler Holder",
    slug: "pyramid-pr-106",
    category: "pyramid-series",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 1530,
    code: "PR-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/18.jpg",
    description: "Pyramid Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-103",
    name: "Towel Rod 600mm",
    slug: "pyramid-pr-103",
    category: "pyramid-series",
    subcategory: "towel-rod",
    finish: "Chrome",
    price: 3960,
    code: "PR-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/23.jpg",
    description: "Pyramid Series Towel Rod with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-102",
    name: "Napkin Ring",
    slug: "pyramid-pr-102",
    category: "pyramid-series",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 2070,
    code: "PR-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/24.jpg",
    description: "Pyramid Series Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-105",
    name: "Liquid Dispenser",
    slug: "pyramid-pr-105",
    category: "pyramid-series",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 3150,
    code: "PR-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/26.jpg",
    description: "Pyramid Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-109",
    name: "Towel Rack 600mm",
    slug: "pyramid-pr-109",
    category: "pyramid-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 10350,
    code: "PR-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/29.jpg",
    description: "Pyramid Series Towel Rack with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },

  {
    id: "pyramid-pr-107",
    name: "Paper Holder With Flap",
    slug: "pyramid-pr-107",
    category: "pyramid-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 3150,
    code: "PR-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/27.jpg",
    description: "Pyramid Series Paper Holder with Flap - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Flap Cover", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "pyramid-pr-108",
    name: "Robe Hook",
    slug: "pyramid-pr-108",
    category: "pyramid-series",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 1350,
    code: "PR-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/28.jpg",
    description: "Pyramid Series Robe Hook with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
];
