import type { Product } from "./types";

export const sigmaSeriesProducts: Product[] = [
  // Sigma Chrome Series
  {
    id: "sigma-si-109",
    name: "Towel Rack | 600mm",
    slug: "sigma-si-109",
    category: "sigma-chrome",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 6300,
    code: "SI-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/127.jpg",
    description: "Sigma Series Towel Rack with Chrome Finish - 600mm",
    material: "Brass",
    features: ["Chrome Finish", "600mm Length", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-101",
    name: "Soap Holder",
    slug: "sigma-si-101",
    category: "sigma-chrome",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1440,
    code: "SI-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/128.jpg",
    description: "Sigma Series Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-102",
    name: "Napkin Ring",
    slug: "sigma-si-102",
    category: "sigma-chrome",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 1350,
    code: "SI-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/129.jpg",
    description: "Sigma Series Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-106",
    name: "Tumbler Holder",
    slug: "sigma-si-106",
    category: "sigma-chrome",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 1620,
    code: "SI-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/130.jpg",
    description: "Sigma Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-105",
    name: "Liquid Dispenser",
    slug: "sigma-si-105",
    category: "sigma-chrome",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 2700,
    code: "SI-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/131.jpg",
    description: "Sigma Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-104",
    name: "Soap Holder",
    slug: "sigma-si-104",
    category: "sigma-chrome",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1710,
    code: "SI-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/133.jpg",
    description: "Sigma Series Soap Holder with Glass and Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Dish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-103",
    name: "Towel Bar | 600mm",
    slug: "sigma-si-103",
    category: "sigma-chrome",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 2850,
    code: "SI-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/134.jpg",
    description: "Sigma Series Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["Chrome Finish", "600mm Length", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-107",
    name: "Paper Holder With Flap",
    slug: "sigma-si-107",
    category: "sigma-chrome",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 2160,
    code: "SI-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/135.jpg",
    description: "Sigma Series Paper Holder With Flap and Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Flap", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-si-108",
    name: "Robe Hook",
    slug: "sigma-si-108",
    category: "sigma-chrome",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 990,
    code: "SI-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/136.jpg",
    description: "Sigma Series Robe Hook with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },

  // Sigma Gold Series
  {
    id: "sigma-sig-109",
    name: "Towel Rack | 600mm",
    slug: "sigma-sig-109",
    category: "sigma-gold",
    subcategory: "towel-rack",
    finish: "PVD Gold",
    price: 9900,
    code: "SI-G-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/137.jpg",
    description: "Sigma Series Towel Rack with PVD Gold Finish - 600mm",
    material: "Brass",
    features: ["PVD Gold Finish", "600mm Length", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-101",
    name: "Soap Holder",
    slug: "sigma-sig-101",
    category: "sigma-gold",
    subcategory: "soap-holder",
    finish: "PVD Gold",
    price: 1900,
    code: "SI-G-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/139.jpg",
    description: "Sigma Series Soap Holder with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-102",
    name: "Napkin Ring",
    slug: "sigma-sig-102",
    category: "sigma-gold",
    subcategory: "napkin-ring",
    finish: "PVD Gold",
    price: 1800,
    code: "SI-G-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/140.jpg",
    description: "Sigma Series Napkin Ring with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-106",
    name: "Tumbler Holder",
    slug: "sigma-sig-106",
    category: "sigma-gold",
    subcategory: "tumbler-holder",
    finish: "PVD Gold",
    price: 1970,
    code: "SI-G-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/141.jpg",
    description: "Sigma Series Tumbler Holder with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-105",
    name: "Liquid Dispenser",
    slug: "sigma-sig-105",
    category: "sigma-gold",
    subcategory: "liquid-dispenser",
    finish: "PVD Gold",
    price: 3600,
    code: "SI-G-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/142.jpg",
    description: "Sigma Series Liquid Dispenser with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-103",
    name: "Towel Bar | 600mm",
    slug: "sigma-sig-103",
    category: "sigma-gold",
    subcategory: "towel-bar",
    finish: "PVD Gold",
    price: 3780,
    code: "SI-G-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/143.jpg",
    description: "Sigma Series Towel Bar with PVD Gold Finish - 600mm",
    material: "Brass",
    features: ["PVD Gold Finish", "600mm Length", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-104",
    name: "Soap Holder",
    slug: "sigma-sig-104",
    category: "sigma-gold",
    subcategory: "soap-holder",
    finish: "PVD Gold",
    price: 2300,
    code: "SI-G-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/144.jpg",
    description: "Sigma Series Soap Holder with Glass and PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Dish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-107",
    name: "Paper Holder With Flap",
    slug: "sigma-sig-107",
    category: "sigma-gold",
    subcategory: "paper-holder",
    finish: "PVD Gold",
    price: 3600,
    code: "SI-G-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/145.jpg",
    description: "Sigma Series Paper Holder With Flap and PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "With Flap", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "sigma-sig-108",
    name: "Robe Hook",
    slug: "sigma-sig-108",
    category: "sigma-gold",
    subcategory: "robe-hook",
    finish: "PVD Gold",
    price: 1200,
    code: "SI-G-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/146.jpg",
    description: "Sigma Series Robe Hook with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },

  // Sigma Rose Gold Series - Placeholder (you mentioned it but didn't provide product details)
  // Add products here when you provide the details
];
