import { Product } from "./types";

// Signature Series Bathroom Accessories - Chrome Finish
export const signatureSeriesProducts: Product[] = [
  {
    id: "signature-sg-109",
    name: "Towel Rack",
    slug: "signature-sg-109",
    category: "signature-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 8400,
    code: "SG-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/32.jpg",
    description: "Signature Series Towel Rack with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-110",
    name: "Towel Rack with Shelf 600mm",
    slug: "signature-sg-110",
    category: "signature-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 10800,
    code: "SG-110",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/33.jpg",
    description: "Signature Series Towel Rack with Shelf - Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "With Shelf", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-101",
    name: "Soap Holder",
    slug: "signature-sg-101",
    category: "signature-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 2610,
    code: "SG-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/34.jpg",
    description: "Signature Series Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-102",
    name: "Napkin Ring",
    slug: "signature-sg-102",
    category: "signature-series",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 2610,
    code: "SG-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/35.jpg",
    description: "Signature Series Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-103",
    name: "Towel Bar 600mm",
    slug: "signature-sg-103",
    category: "signature-series",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 5700,
    code: "SG-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/36.jpg",
    description: "Signature Series Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-104",
    name: "Tumbler Holder",
    slug: "signature-sg-104",
    category: "signature-series",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 2700,
    code: "SG-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/37.jpg",
    description: "Signature Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-105",
    name: "Liquid Dispenser",
    slug: "signature-sg-105",
    category: "signature-series",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 3600,
    code: "SG-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/39.jpg",
    description: "Signature Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-106",
    name: "Paper Holder",
    slug: "signature-sg-106",
    category: "signature-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 1800,
    code: "SG-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/40.jpg",
    description: "Signature Series Paper Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-107",
    name: "Roll Holder With Mobile Stand",
    slug: "signature-sg-107",
    category: "signature-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 3600,
    code: "SG-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/41.jpg",
    description: "Signature Series Roll Holder with Mobile Stand - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Mobile Stand", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "signature-sg-108",
    name: "Robe Hook",
    slug: "signature-sg-108",
    category: "signature-series",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 990,
    code: "SG-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/38.jpg",
    description: "Signature Series Robe Hook with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
];
