import { Product } from "./types";

// Solitaire Series Bathroom Accessories - Chrome Finish
export const solitaireSeriesProducts: Product[] = [
  {
    id: "solitaire-slt-111a",
    name: "Towel Rack 600mm",
    slug: "solitaire-slt-111a",
    category: "solitaire-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 8550,
    code: "SLT-111-A",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/51.jpg",
    description: "Solitaire Series Towel Rack with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-111b",
    name: "Towel Rack 450mm",
    slug: "solitaire-slt-111b",
    category: "solitaire-series",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 7850,
    code: "SLT-111-B",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/51.jpg",
    description: "Solitaire Series Towel Rack with Chrome Finish - 450mm",
    material: "Brass",
    features: ["450mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-101",
    name: "Soap Holder",
    slug: "solitaire-slt-101",
    category: "solitaire-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1630,
    code: "SLT-101",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/52.jpg",
    description: "Solitaire Series Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-102",
    name: "Napkin Ring",
    slug: "solitaire-slt-102",
    category: "solitaire-series",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 1800,
    code: "SLT-102",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/53.jpg",
    description: "Solitaire Series Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-103a",
    name: "Towel Bar 600mm",
    slug: "solitaire-slt-103a",
    category: "solitaire-series",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 2970,
    code: "SLT-103A",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/54.jpg",
    description: "Solitaire Series Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-103b",
    name: "Towel Bar 450mm",
    slug: "solitaire-slt-103b",
    category: "solitaire-series",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 2700,
    code: "SLT-103B",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/54.jpg",
    description: "Solitaire Series Towel Bar with Chrome Finish - 450mm",
    material: "Brass",
    features: ["450mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-104",
    name: "Soap Holder with Glass",
    slug: "solitaire-slt-104",
    category: "solitaire-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1350,
    code: "SLT-104",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/55.jpg",
    description: "Solitaire Series Soap Holder with Glass - Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Insert", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-105",
    name: "Liquid Dispenser",
    slug: "solitaire-slt-105",
    category: "solitaire-series",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 1530,
    code: "SLT-105",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/56.jpg",
    description: "Solitaire Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-106",
    name: "Tumbler Holder",
    slug: "solitaire-slt-106",
    category: "solitaire-series",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 1430,
    code: "SLT-106",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/57.jpg",
    description: "Solitaire Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-107",
    name: "Paper Holder With Flap",
    slug: "solitaire-slt-107",
    category: "solitaire-series",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 2430,
    code: "SLT-107",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/58.jpg",
    description: "Solitaire Series Paper Holder with Flap - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Flap Cover", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-108",
    name: "Robe Hook",
    slug: "solitaire-slt-108",
    category: "solitaire-series",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 1260,
    code: "SLT-108",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/59.jpg",
    description: "Solitaire Series Robe Hook with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-109",
    name: "Dual Soap Dish",
    slug: "solitaire-slt-109",
    category: "solitaire-series",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 2880,
    code: "SLT-109",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/61.jpg",
    description: "Solitaire Series Dual Soap Dish with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Dual Compartments", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-tid",
    name: "Soap + Tumbler Holder",
    slug: "solitaire-slt-tid",
    category: "solitaire-series",
    subcategory: "combination-holder",
    finish: "Chrome",
    price: 2880,
    code: "SLT-TID",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/62.jpg",
    description: "Solitaire Series Soap + Tumbler Holder Combination - Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "2-in-1 Holder", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "solitaire-slt-112",
    name: "Liquid Dispenser + Tumbler Holder",
    slug: "solitaire-slt-112",
    category: "solitaire-series",
    subcategory: "combination-holder",
    finish: "Chrome",
    price: 2880,
    code: "SLT-112",
    image: "https://joywater2026.vercel.app/JOY%20WATER%20BATHROOM%20ACCESSORIES%20(1)/63.jpg",
    description: "Solitaire Series Liquid Dispenser + Tumbler Holder Combination - Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "2-in-1 Holder", "Premium Brass Construction", "11 Years Warranty"]
  },
];
