import { Product } from "./types";

// Supreme Series Bathroom Accessories - Chrome, PVD Gold, and PVD Rose Gold Finishes
export const supremeSeriesProducts: Product[] = [
  // CHROME FINISH SERIES
  {
    id: "supreme-sp-108",
    name: "Towel Rack",
    slug: "supreme-sp-108",
    category: "supreme-chrome",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 8730,
    code: "SP-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/120.jpg",
    description: "Supreme Series Towel Rack with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-105",
    name: "Liquid Dispenser",
    slug: "supreme-sp-105",
    category: "supreme-chrome",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 3780,
    code: "SP-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/121.jpg",
    description: "Supreme Series Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-104",
    name: "Tumbler Holder",
    slug: "supreme-sp-104",
    category: "supreme-chrome",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 2970,
    code: "SP-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/123.jpg",
    description: "Supreme Series Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-102",
    name: "Napkin Ring",
    slug: "supreme-sp-102",
    category: "supreme-chrome",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 3150,
    code: "SP-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/122.jpg",
    description: "Supreme Series Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-101",
    name: "Soap Holder",
    slug: "supreme-sp-101",
    category: "supreme-chrome",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 2880,
    code: "SP-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/92.jpg",
    description: "Supreme Series Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-103",
    name: "Towel Bar 600mm",
    slug: "supreme-sp-103",
    category: "supreme-chrome",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 4860,
    code: "SP-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/98.jpg",
    description: "Supreme Series Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-106",
    name: "Paper Holder With Flap",
    slug: "supreme-sp-106",
    category: "supreme-chrome",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 3600,
    code: "SP-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/125.jpg",
    description: "Supreme Series Paper Holder with Flap - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Flap Cover", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-107",
    name: "Robe Hook",
    slug: "supreme-sp-107",
    category: "supreme-chrome",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 2160,
    code: "SP-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/126.jpg",
    description: "Supreme Series Robe Hook with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction", "11 Years Warranty"]
  },

  // PVD GOLD FINISH SERIES
  {
    id: "supreme-sp-g-108",
    name: "Towel Rack Double",
    slug: "supreme-sp-g-108",
    category: "supreme-gold",
    subcategory: "towel-rack",
    finish: "PVD Gold",
    price: 13500,
    code: "SP-G-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/66.jpg",
    description: "Supreme Series Double Towel Rack with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Double Rack", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-101",
    name: "Soap Holder",
    slug: "supreme-sp-g-101",
    category: "supreme-gold",
    subcategory: "soap-holder",
    finish: "PVD Gold",
    price: 3600,
    code: "SP-G-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/67.jpg",
    description: "Supreme Series Soap Holder with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-102",
    name: "Napkin Ring",
    slug: "supreme-sp-g-102",
    category: "supreme-gold",
    subcategory: "napkin-ring",
    finish: "PVD Gold",
    price: 4230,
    code: "SP-G-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/107.jpg",
    description: "Supreme Series Napkin Ring with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-104",
    name: "Tumbler Holder",
    slug: "supreme-sp-g-104",
    category: "supreme-gold",
    subcategory: "tumbler-holder",
    finish: "PVD Gold",
    price: 3870,
    code: "SP-G-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/108.jpg",
    description: "Supreme Series Tumbler Holder with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-105",
    name: "Liquid Dispenser",
    slug: "supreme-sp-g-105",
    category: "supreme-gold",
    subcategory: "liquid-dispenser",
    finish: "PVD Gold",
    price: 4770,
    code: "SP-G-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/109.jpg",
    description: "Supreme Series Liquid Dispenser with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-106",
    name: "Paper Holder With Flap",
    slug: "supreme-sp-g-106",
    category: "supreme-gold",
    subcategory: "paper-holder",
    finish: "PVD Gold",
    price: 4950,
    code: "SP-G-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/111.jpg",
    description: "Supreme Series Paper Holder with Flap - PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "With Flap Cover", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-g-107",
    name: "Robe Hook",
    slug: "supreme-sp-g-107",
    category: "supreme-gold",
    subcategory: "robe-hook",
    finish: "PVD Gold",
    price: 2890,
    code: "SP-G-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/112.jpg",
    description: "Supreme Series Robe Hook with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },

  // PVD ROSE GOLD FINISH SERIES
  {
    id: "supreme-sp-rg-108",
    name: "Towel Rack",
    slug: "supreme-sp-rg-108",
    category: "supreme-rose-gold",
    subcategory: "towel-rack",
    finish: "PVD Rose Gold",
    price: 13500,
    code: "SP-RG-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/113.jpg",
    description: "Supreme Series Towel Rack with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-102",
    name: "Napkin Ring",
    slug: "supreme-sp-rg-102",
    category: "supreme-rose-gold",
    subcategory: "napkin-ring",
    finish: "PVD Rose Gold",
    price: 4230,
    code: "SP-RG-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/114.jpg",
    description: "Supreme Series Napkin Ring with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-104",
    name: "Tumbler Holder",
    slug: "supreme-sp-rg-104",
    category: "supreme-rose-gold",
    subcategory: "tumbler-holder",
    finish: "PVD Rose Gold",
    price: 3870,
    code: "SP-RG-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/115.jpg",
    description: "Supreme Series Tumbler Holder with PVD Rose Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Rose Gold Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-105",
    name: "Liquid Dispenser",
    slug: "supreme-sp-rg-105",
    category: "supreme-rose-gold",
    subcategory: "liquid-dispenser",
    finish: "PVD Rose Gold",
    price: 4770,
    code: "SP-RG-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/116.jpg",
    description: "Supreme Series Liquid Dispenser with PVD Rose Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Rose Gold Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-101",
    name: "Soap Holder",
    slug: "supreme-sp-rg-101",
    category: "supreme-rose-gold",
    subcategory: "soap-holder",
    finish: "PVD Rose Gold",
    price: 3800,
    code: "SP-RG-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/81.jpg",
    description: "Supreme Series Soap Holder with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-103",
    name: "Towel Bar 600mm",
    slug: "supreme-sp-rg-103",
    category: "supreme-rose-gold",
    subcategory: "towel-bar",
    finish: "PVD Rose Gold",
    price: 6750,
    code: "SP-RG-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/86.jpg",
    description: "Supreme Series Towel Bar with PVD Rose Gold Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "PVD Rose Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-106",
    name: "Paper Holder With Flap",
    slug: "supreme-sp-rg-106",
    category: "supreme-rose-gold",
    subcategory: "paper-holder",
    finish: "PVD Rose Gold",
    price: 4950,
    code: "SP-RG-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/118.jpg",
    description: "Supreme Series Paper Holder with Flap - PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "With Flap Cover", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "supreme-sp-rg-107",
    name: "Robe Hook",
    slug: "supreme-sp-rg-107",
    category: "supreme-rose-gold",
    subcategory: "robe-hook",
    finish: "PVD Rose Gold",
    price: 2890,
    code: "SP-RG-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/119.jpg",
    description: "Supreme Series Robe Hook with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
];
