import { Product } from "./types";

// Swatch Series Bathroom Accessories - Chrome, Gold, and Rose Gold Finishes
export const swatchSeriesProducts: Product[] = [
  // CHROME FINISH SERIES
  {
    id: "swatch-sw-109a",
    name: "Towel Rack 600mm",
    slug: "swatch-sw-109a",
    category: "swatch-chrome",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 7200,
    code: "SW-109A",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/64.jpg",
    description: "Brass Towel Rack with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-109b",
    name: "Towel Rack 450mm",
    slug: "swatch-sw-109b",
    category: "swatch-chrome",
    subcategory: "towel-rack",
    finish: "Chrome",
    price: 7000,
    code: "SW-109B",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/64.jpg",
    description: "Brass Towel Rack with Chrome Finish - 450mm",
    material: "Brass",
    features: ["450mm Length", "Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-101",
    name: "Soap Holder",
    slug: "swatch-sw-101",
    category: "swatch-chrome",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1350,
    code: "SW-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/65.jpg",
    description: "Brass Soap Holder with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-102",
    name: "Napkin Ring",
    slug: "swatch-sw-102",
    category: "swatch-chrome",
    subcategory: "napkin-ring",
    finish: "Chrome",
    price: 1350,
    code: "SW-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/68.jpg",
    description: "Brass Napkin Ring with Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-103a",
    name: "Towel Bar 600mm",
    slug: "swatch-sw-103a",
    category: "swatch-chrome",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 2590,
    code: "SW-103A",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/69.jpg",
    description: "Brass Towel Bar with Chrome Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-103b",
    name: "Towel Bar 450mm",
    slug: "swatch-sw-103b",
    category: "swatch-chrome",
    subcategory: "towel-bar",
    finish: "Chrome",
    price: 2450,
    code: "SW-103B",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/69.jpg",
    description: "Brass Towel Bar with Chrome Finish - 450mm",
    material: "Brass",
    features: ["450mm Length", "Chrome Finish", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-104",
    name: "Soap Holder with Glass",
    slug: "swatch-sw-104",
    category: "swatch-chrome",
    subcategory: "soap-holder",
    finish: "Chrome",
    price: 1350,
    code: "SW-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/70.jpg",
    description: "Brass + Glass Soap Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Insert", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-106",
    name: "Tumbler Holder",
    slug: "swatch-sw-106",
    category: "swatch-chrome",
    subcategory: "tumbler-holder",
    finish: "Chrome",
    price: 1575,
    code: "SW-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/72.jpg",
    description: "Brass + Glass Tumbler Holder with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Tumbler", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-105",
    name: "Liquid Dispenser",
    slug: "swatch-sw-105",
    category: "swatch-chrome",
    subcategory: "liquid-dispenser",
    finish: "Chrome",
    price: 2250,
    code: "SW-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/73.jpg",
    description: "Brass + Glass Liquid Dispenser with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Container", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-107",
    name: "Paper Holder With Flap",
    slug: "swatch-sw-107",
    category: "swatch-chrome",
    subcategory: "paper-holder",
    finish: "Chrome",
    price: 2300,
    code: "SW-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/74.jpg",
    description: "Brass Paper Holder with Flap - Chrome Finish",
    material: "Brass",
    features: ["Chrome Finish", "With Flap Cover", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-108",
    name: "Robe Hook",
    slug: "swatch-sw-108",
    category: "swatch-chrome",
    subcategory: "robe-hook",
    finish: "Chrome",
    price: 900,
    code: "SW-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/75.jpg",
    description: "Brass + Glass Robe Hook with Chrome Finish",
    material: "Brass + Glass",
    features: ["Chrome Finish", "Glass Accent", "Premium Brass Construction"]
  },

  // PVD GOLD FINISH SERIES
  {
    id: "swatch-sw-g-109",
    name: "Towel Rack",
    slug: "swatch-sw-g-109",
    category: "swatch-gold",
    subcategory: "towel-rack",
    finish: "PVD Gold",
    price: 9900,
    code: "SW-G-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/76.jpg",
    description: "Brass Towel Rack with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-g-102",
    name: "Napkin Ring",
    slug: "swatch-sw-g-102",
    category: "swatch-gold",
    subcategory: "napkin-ring",
    finish: "PVD Gold",
    price: 1800,
    code: "SW-G-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/77.jpg",
    description: "Brass Napkin Ring with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-g-103",
    name: "Towel Bar",
    slug: "swatch-sw-g-103",
    category: "swatch-gold",
    subcategory: "towel-bar",
    finish: "PVD Gold",
    price: 3780,
    code: "SW-G-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/79.jpg",
    description: "Brass Towel Bar with PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-g-104",
    name: "Soap Holder",
    slug: "swatch-sw-g-104",
    category: "swatch-gold",
    subcategory: "soap-holder",
    finish: "PVD Gold",
    price: 2300,
    code: "SW-G-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/80.jpg",
    description: "Brass + Glass Soap Holder with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Insert", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-g-106",
    name: "Tumbler Holder",
    slug: "swatch-sw-g-106",
    category: "swatch-gold",
    subcategory: "tumbler-holder",
    finish: "PVD Gold",
    price: 1970,
    code: "SW-G-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/82.jpg",
    description: "Brass + Glass Tumbler Holder with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Tumbler", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-g-105",
    name: "Liquid Dispenser",
    slug: "swatch-sw-g-105",
    category: "swatch-gold",
    subcategory: "liquid-dispenser",
    finish: "PVD Gold",
    price: 3600,
    code: "SW-G-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/83.jpg",
    description: "Brass + Glass Liquid Dispenser with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Container", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-g-107",
    name: "Paper Holder With Flap",
    slug: "swatch-sw-g-107",
    category: "swatch-gold",
    subcategory: "paper-holder",
    finish: "PVD Gold",
    price: 3500,
    code: "SW-G-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/84.jpg",
    description: "Brass Paper Holder with Flap - PVD Gold Finish",
    material: "Brass",
    features: ["PVD Gold Finish", "With Flap Cover", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-g-108",
    name: "Robe Hook",
    slug: "swatch-sw-g-108",
    category: "swatch-gold",
    subcategory: "robe-hook",
    finish: "PVD Gold",
    price: 1200,
    code: "SW-G-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/85.jpg",
    description: "Brass + Glass Robe Hook with PVD Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Gold Finish", "Glass Accent", "Premium Brass Construction"]
  },

  // PVD ROSE GOLD FINISH SERIES
  {
    id: "swatch-sw-rg-109",
    name: "Towel Rack",
    slug: "swatch-sw-rg-109",
    category: "swatch-rose-gold",
    subcategory: "towel-rack",
    finish: "PVD Rose Gold",
    price: 9990,
    code: "SW-RG-109",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/87.jpg",
    description: "Brass Towel Rack with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-101",
    name: "Soap Holder",
    slug: "swatch-sw-rg-101",
    category: "swatch-rose-gold",
    subcategory: "soap-holder",
    finish: "PVD Rose Gold",
    price: 1900,
    code: "SW-RG-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/88.jpg",
    description: "Brass Soap Holder with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-102",
    name: "Napkin Ring",
    slug: "swatch-sw-rg-102",
    category: "swatch-rose-gold",
    subcategory: "napkin-ring",
    finish: "PVD Rose Gold",
    price: 1800,
    code: "SW-RG-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/89.jpg",
    description: "Brass Napkin Ring with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-103",
    name: "Towel Bar",
    slug: "swatch-sw-rg-103",
    category: "swatch-rose-gold",
    subcategory: "towel-bar",
    finish: "PVD Rose Gold",
    price: 3780,
    code: "SW-RG-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/90.jpg",
    description: "Brass Towel Bar with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-104",
    name: "Soap Holder with Glass",
    slug: "swatch-sw-rg-104",
    category: "swatch-rose-gold",
    subcategory: "soap-holder",
    finish: "PVD Rose Gold",
    price: 2300,
    code: "SW-RG-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/91.jpg",
    description: "Brass + Glass Soap Holder with PVD Rose Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Rose Gold Finish", "Glass Insert", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-rg-106",
    name: "Tumbler Holder",
    slug: "swatch-sw-rg-106",
    category: "swatch-rose-gold",
    subcategory: "tumbler-holder",
    finish: "PVD Rose Gold",
    price: 1970,
    code: "SW-RG-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/93.jpg",
    description: "Brass Tumbler Holder with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-105",
    name: "Liquid Dispenser",
    slug: "swatch-sw-rg-105",
    category: "swatch-rose-gold",
    subcategory: "liquid-dispenser",
    finish: "PVD Rose Gold",
    price: 3600,
    code: "SW-RG-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/94.jpg",
    description: "Brass Liquid Dispenser with PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "Premium Brass Construction", "Durable Coating"]
  },
  {
    id: "swatch-sw-rg-107",
    name: "Paper Holder With Flap",
    slug: "swatch-sw-rg-107",
    category: "swatch-rose-gold",
    subcategory: "paper-holder",
    finish: "PVD Rose Gold",
    price: 3600,
    code: "SW-RG-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/95.jpg",
    description: "Brass Paper Holder with Flap - PVD Rose Gold Finish",
    material: "Brass",
    features: ["PVD Rose Gold Finish", "With Flap Cover", "Premium Brass Construction"]
  },
  {
    id: "swatch-sw-rg-108",
    name: "Robe Hook",
    slug: "swatch-sw-rg-108",
    category: "swatch-rose-gold",
    subcategory: "robe-hook",
    finish: "PVD Rose Gold",
    price: 1200,
    code: "SW-RG-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/96.jpg",
    description: "Brass + Glass Robe Hook with PVD Rose Gold Finish",
    material: "Brass + Glass",
    features: ["PVD Rose Gold Finish", "Glass Accent", "Premium Brass Construction"]
  },
];
