import { Product } from "./types";

// Unity Series Bathroom Accessories - Black Gold Finish
export const unitySeriesProducts: Product[] = [
  {
    id: "unity-un-bg-108",
    name: "Towel Rack 600mm",
    slug: "unity-un-bg-108",
    category: "unity-series",
    subcategory: "towel-rack",
    finish: "Black Gold",
    price: 8100,
    code: "UN-BG-108",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/97.jpg",
    description: "Unity Series Towel Rack with Black Gold Finish - 600mm",
    material: "Brass",
    features: ["600mm Length", "Black Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-102",
    name: "Napkin Ring",
    slug: "unity-un-bg-102",
    category: "unity-series",
    subcategory: "napkin-ring",
    finish: "Black Gold",
    price: 3870,
    code: "UN-BG-102",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/100.jpg",
    description: "Unity Series Napkin Ring with Black Gold Finish",
    material: "Brass",
    features: ["Black Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-103",
    name: "Towel Bar",
    slug: "unity-un-bg-103",
    category: "unity-series",
    subcategory: "towel-bar",
    finish: "Black Gold",
    price: 4230,
    code: "UN-BG-103",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/99.jpg",
    description: "Unity Series Towel Bar with Black Gold Finish",
    material: "Brass",
    features: ["Black Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-105",
    name: "Tumbler Holder",
    slug: "unity-un-bg-105",
    category: "unity-series",
    subcategory: "tumbler-holder",
    finish: "Black Gold",
    price: 2700,
    code: "UN-BG-105",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/101.jpg",
    description: "Unity Series Tumbler Holder with Black Gold Finish",
    material: "Brass + Glass",
    features: ["Black Gold Finish", "Glass Tumbler", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-104",
    name: "Liquid Dispenser",
    slug: "unity-un-bg-104",
    category: "unity-series",
    subcategory: "liquid-dispenser",
    finish: "Black Gold",
    price: 3870,
    code: "UN-BG-104",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/102.jpg",
    description: "Unity Series Liquid Dispenser with Black Gold Finish",
    material: "Brass + Glass",
    features: ["Black Gold Finish", "Glass Container", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-101",
    name: "Glass Soap Dish",
    slug: "unity-un-bg-101",
    category: "unity-series",
    subcategory: "soap-holder",
    finish: "Black Gold",
    price: 2700,
    code: "UN-BG-101",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/104.jpg",
    description: "Unity Series Glass Soap Dish with Black Gold Finish",
    material: "Brass + Glass",
    features: ["Black Gold Finish", "Glass Dish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-106",
    name: "Paper Holder",
    slug: "unity-un-bg-106",
    category: "unity-series",
    subcategory: "paper-holder",
    finish: "Black Gold",
    price: 3150,
    code: "UN-BG-106",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/105.jpg",
    description: "Unity Series Paper Holder with Black Gold Finish",
    material: "Brass",
    features: ["Black Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
  {
    id: "unity-un-bg-107",
    name: "Robe Hook",
    slug: "unity-un-bg-107",
    category: "unity-series",
    subcategory: "robe-hook",
    finish: "Black Gold",
    price: 2070,
    code: "UN-BG-107",
    image: "/JOY WATER BATHROOM ACCESSORIES (1)/103.jpg",
    description: "Unity Series Robe Hook with Black Gold Finish",
    material: "Brass",
    features: ["Black Gold Finish", "Premium Brass Construction", "11 Years Warranty"]
  },
];
