/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CareRouteImport } from './routes/care'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MySelectionsRouteImport } from './routes/my-selections'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DivertersMixersInFinishSlugRouteImport } from './routes/diverters-mixers-in-finish.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShowersInFinishSlugRouteImport } from './routes/showers-in-finish.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MySelectionsRoute = MySelectionsRouteImport.update({
  id: '/my-selections',
  path: '/my-selections',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DivertersMixersInFinishSlugRoute =
  DivertersMixersInFinishSlugRouteImport.update({
    id: '/diverters-mixers-in-finish/$slug',
    path: '/diverters-mixers-in-finish/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowersInFinishSlugRoute = ShowersInFinishSlugRouteImport.update({
  id: '/showers-in-finish/$slug',
  path: '/showers-in-finish/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/my-selections': typeof MySelectionsRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/my-selections': typeof MySelectionsRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/my-selections': typeof MySelectionsRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/care'
    | '/contact'
    | '/my-selections'
    | '/products'
    | '/sitemap.xml'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/care'
    | '/contact'
    | '/my-selections'
    | '/products'
    | '/sitemap.xml'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/care'
    | '/contact'
    | '/my-selections'
    | '/products'
    | '/sitemap.xml'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareRoute: typeof CareRoute
  ContactRoute: typeof ContactRoute
  MySelectionsRoute: typeof MySelectionsRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WarrantyRoute: typeof WarrantyRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DivertersMixersInFinishSlugRoute: typeof DivertersMixersInFinishSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShowersInFinishSlugRoute: typeof ShowersInFinishSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-selections': {
      id: '/my-selections'
      path: '/my-selections'
      fullPath: '/my-selections'
      preLoaderRoute: typeof MySelectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diverters-mixers-in-finish/$slug': {
      id: '/diverters-mixers-in-finish/$slug'
      path: '/diverters-mixers-in-finish/$slug'
      fullPath: '/diverters-mixers-in-finish/$slug'
      preLoaderRoute: typeof DivertersMixersInFinishSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showers-in-finish/$slug': {
      id: '/showers-in-finish/$slug'
      path: '/showers-in-finish/$slug'
      fullPath: '/showers-in-finish/$slug'
      preLoaderRoute: typeof ShowersInFinishSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareRoute: CareRoute,
  ContactRoute: ContactRoute,
  MySelectionsRoute: MySelectionsRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WarrantyRoute: WarrantyRoute,
  CategorySlugRoute: CategorySlugRoute,
  DivertersMixersInFinishSlugRoute: DivertersMixersInFinishSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShowersInFinishSlugRoute: ShowersInFinishSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
