/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BathroomAccessoriesRouteImport } from './routes/bathroom-accessories'
import { Route as CareRouteImport } from './routes/care'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FortuneSeriesRouteImport } from './routes/fortune-series'
import { Route as OysterBlackRouteImport } from './routes/oyster-black'
import { Route as OysterChromeRouteImport } from './routes/oyster-chrome'
import { Route as OysterRoseGoldRouteImport } from './routes/oyster-rose-gold'
import { Route as OysterSeriesRouteImport } from './routes/oyster-series'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PyramidSeriesRouteImport } from './routes/pyramid-series'
import { Route as SigmaChromeRouteImport } from './routes/sigma-chrome'
import { Route as SigmaGoldRouteImport } from './routes/sigma-gold'
import { Route as SigmaRoseGoldRouteImport } from './routes/sigma-rose-gold'
import { Route as SigmaSeriesRouteImport } from './routes/sigma-series'
import { Route as SignatureSeriesRouteImport } from './routes/signature-series'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SolitaireSeriesRouteImport } from './routes/solitaire-series'
import { Route as SupremeChromeRouteImport } from './routes/supreme-chrome'
import { Route as SupremeGoldRouteImport } from './routes/supreme-gold'
import { Route as SupremeRoseGoldRouteImport } from './routes/supreme-rose-gold'
import { Route as SwatchChromeRouteImport } from './routes/swatch-chrome'
import { Route as SwatchGoldRouteImport } from './routes/swatch-gold'
import { Route as SwatchRoseGoldRouteImport } from './routes/swatch-rose-gold'
import { Route as SwatchSeriesRouteImport } from './routes/swatch-series'
import { Route as UnitySeriesRouteImport } from './routes/unity-series'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DivertersMixersInFinishSlugRouteImport } from './routes/diverters-mixers-in-finish.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ShowersInFinishSlugRouteImport } from './routes/showers-in-finish.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BathroomAccessoriesRoute = BathroomAccessoriesRouteImport.update({
  id: '/bathroom-accessories',
  path: '/bathroom-accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FortuneSeriesRoute = FortuneSeriesRouteImport.update({
  id: '/fortune-series',
  path: '/fortune-series',
  getParentRoute: () => rootRouteImport,
} as any)
const OysterBlackRoute = OysterBlackRouteImport.update({
  id: '/oyster-black',
  path: '/oyster-black',
  getParentRoute: () => rootRouteImport,
} as any)
const OysterChromeRoute = OysterChromeRouteImport.update({
  id: '/oyster-chrome',
  path: '/oyster-chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const OysterRoseGoldRoute = OysterRoseGoldRouteImport.update({
  id: '/oyster-rose-gold',
  path: '/oyster-rose-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const OysterSeriesRoute = OysterSeriesRouteImport.update({
  id: '/oyster-series',
  path: '/oyster-series',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PyramidSeriesRoute = PyramidSeriesRouteImport.update({
  id: '/pyramid-series',
  path: '/pyramid-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaChromeRoute = SigmaChromeRouteImport.update({
  id: '/sigma-chrome',
  path: '/sigma-chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaGoldRoute = SigmaGoldRouteImport.update({
  id: '/sigma-gold',
  path: '/sigma-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaRoseGoldRoute = SigmaRoseGoldRouteImport.update({
  id: '/sigma-rose-gold',
  path: '/sigma-rose-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SigmaSeriesRoute = SigmaSeriesRouteImport.update({
  id: '/sigma-series',
  path: '/sigma-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SignatureSeriesRoute = SignatureSeriesRouteImport.update({
  id: '/signature-series',
  path: '/signature-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SolitaireSeriesRoute = SolitaireSeriesRouteImport.update({
  id: '/solitaire-series',
  path: '/solitaire-series',
  getParentRoute: () => rootRouteImport,
} as any)
const SupremeChromeRoute = SupremeChromeRouteImport.update({
  id: '/supreme-chrome',
  path: '/supreme-chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const SupremeGoldRoute = SupremeGoldRouteImport.update({
  id: '/supreme-gold',
  path: '/supreme-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SupremeRoseGoldRoute = SupremeRoseGoldRouteImport.update({
  id: '/supreme-rose-gold',
  path: '/supreme-rose-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SwatchChromeRoute = SwatchChromeRouteImport.update({
  id: '/swatch-chrome',
  path: '/swatch-chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const SwatchGoldRoute = SwatchGoldRouteImport.update({
  id: '/swatch-gold',
  path: '/swatch-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SwatchRoseGoldRoute = SwatchRoseGoldRouteImport.update({
  id: '/swatch-rose-gold',
  path: '/swatch-rose-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SwatchSeriesRoute = SwatchSeriesRouteImport.update({
  id: '/swatch-series',
  path: '/swatch-series',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitySeriesRoute = UnitySeriesRouteImport.update({
  id: '/unity-series',
  path: '/unity-series',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DivertersMixersInFinishSlugRoute =
  DivertersMixersInFinishSlugRouteImport.update({
    id: '/diverters-mixers-in-finish/$slug',
    path: '/diverters-mixers-in-finish/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowersInFinishSlugRoute = ShowersInFinishSlugRouteImport.update({
  id: '/showers-in-finish/$slug',
  path: '/showers-in-finish/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-accessories': typeof BathroomAccessoriesRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/fortune-series': typeof FortuneSeriesRoute
  '/oyster-black': typeof OysterBlackRoute
  '/oyster-chrome': typeof OysterChromeRoute
  '/oyster-rose-gold': typeof OysterRoseGoldRoute
  '/oyster-series': typeof OysterSeriesRoute
  '/products': typeof ProductsRoute
  '/pyramid-series': typeof PyramidSeriesRoute
  '/sigma-chrome': typeof SigmaChromeRoute
  '/sigma-gold': typeof SigmaGoldRoute
  '/sigma-rose-gold': typeof SigmaRoseGoldRoute
  '/sigma-series': typeof SigmaSeriesRoute
  '/signature-series': typeof SignatureSeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitaire-series': typeof SolitaireSeriesRoute
  '/supreme-chrome': typeof SupremeChromeRoute
  '/supreme-gold': typeof SupremeGoldRoute
  '/supreme-rose-gold': typeof SupremeRoseGoldRoute
  '/swatch-chrome': typeof SwatchChromeRoute
  '/swatch-gold': typeof SwatchGoldRoute
  '/swatch-rose-gold': typeof SwatchRoseGoldRoute
  '/swatch-series': typeof SwatchSeriesRoute
  '/unity-series': typeof UnitySeriesRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-accessories': typeof BathroomAccessoriesRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/fortune-series': typeof FortuneSeriesRoute
  '/oyster-black': typeof OysterBlackRoute
  '/oyster-chrome': typeof OysterChromeRoute
  '/oyster-rose-gold': typeof OysterRoseGoldRoute
  '/oyster-series': typeof OysterSeriesRoute
  '/products': typeof ProductsRoute
  '/pyramid-series': typeof PyramidSeriesRoute
  '/sigma-chrome': typeof SigmaChromeRoute
  '/sigma-gold': typeof SigmaGoldRoute
  '/sigma-rose-gold': typeof SigmaRoseGoldRoute
  '/sigma-series': typeof SigmaSeriesRoute
  '/signature-series': typeof SignatureSeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitaire-series': typeof SolitaireSeriesRoute
  '/supreme-chrome': typeof SupremeChromeRoute
  '/supreme-gold': typeof SupremeGoldRoute
  '/supreme-rose-gold': typeof SupremeRoseGoldRoute
  '/swatch-chrome': typeof SwatchChromeRoute
  '/swatch-gold': typeof SwatchGoldRoute
  '/swatch-rose-gold': typeof SwatchRoseGoldRoute
  '/swatch-series': typeof SwatchSeriesRoute
  '/unity-series': typeof UnitySeriesRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bathroom-accessories': typeof BathroomAccessoriesRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/fortune-series': typeof FortuneSeriesRoute
  '/oyster-black': typeof OysterBlackRoute
  '/oyster-chrome': typeof OysterChromeRoute
  '/oyster-rose-gold': typeof OysterRoseGoldRoute
  '/oyster-series': typeof OysterSeriesRoute
  '/products': typeof ProductsRoute
  '/pyramid-series': typeof PyramidSeriesRoute
  '/sigma-chrome': typeof SigmaChromeRoute
  '/sigma-gold': typeof SigmaGoldRoute
  '/sigma-rose-gold': typeof SigmaRoseGoldRoute
  '/sigma-series': typeof SigmaSeriesRoute
  '/signature-series': typeof SignatureSeriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solitaire-series': typeof SolitaireSeriesRoute
  '/supreme-chrome': typeof SupremeChromeRoute
  '/supreme-gold': typeof SupremeGoldRoute
  '/supreme-rose-gold': typeof SupremeRoseGoldRoute
  '/swatch-chrome': typeof SwatchChromeRoute
  '/swatch-gold': typeof SwatchGoldRoute
  '/swatch-rose-gold': typeof SwatchRoseGoldRoute
  '/swatch-series': typeof SwatchSeriesRoute
  '/unity-series': typeof UnitySeriesRoute
  '/warranty': typeof WarrantyRoute
  '/category/$slug': typeof CategorySlugRoute
  '/diverters-mixers-in-finish/$slug': typeof DivertersMixersInFinishSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/showers-in-finish/$slug': typeof ShowersInFinishSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bathroom-accessories'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/fortune-series'
    | '/oyster-black'
    | '/oyster-chrome'
    | '/oyster-rose-gold'
    | '/oyster-series'
    | '/products'
    | '/pyramid-series'
    | '/sigma-chrome'
    | '/sigma-gold'
    | '/sigma-rose-gold'
    | '/sigma-series'
    | '/signature-series'
    | '/sitemap.xml'
    | '/solitaire-series'
    | '/supreme-chrome'
    | '/supreme-gold'
    | '/supreme-rose-gold'
    | '/swatch-chrome'
    | '/swatch-gold'
    | '/swatch-rose-gold'
    | '/swatch-series'
    | '/unity-series'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bathroom-accessories'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/fortune-series'
    | '/oyster-black'
    | '/oyster-chrome'
    | '/oyster-rose-gold'
    | '/oyster-series'
    | '/products'
    | '/pyramid-series'
    | '/sigma-chrome'
    | '/sigma-gold'
    | '/sigma-rose-gold'
    | '/sigma-series'
    | '/signature-series'
    | '/sitemap.xml'
    | '/solitaire-series'
    | '/supreme-chrome'
    | '/supreme-gold'
    | '/supreme-rose-gold'
    | '/swatch-chrome'
    | '/swatch-gold'
    | '/swatch-rose-gold'
    | '/swatch-series'
    | '/unity-series'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bathroom-accessories'
    | '/care'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/fortune-series'
    | '/oyster-black'
    | '/oyster-chrome'
    | '/oyster-rose-gold'
    | '/oyster-series'
    | '/products'
    | '/pyramid-series'
    | '/sigma-chrome'
    | '/sigma-gold'
    | '/sigma-rose-gold'
    | '/sigma-series'
    | '/signature-series'
    | '/sitemap.xml'
    | '/solitaire-series'
    | '/supreme-chrome'
    | '/supreme-gold'
    | '/supreme-rose-gold'
    | '/swatch-chrome'
    | '/swatch-gold'
    | '/swatch-rose-gold'
    | '/swatch-series'
    | '/unity-series'
    | '/warranty'
    | '/category/$slug'
    | '/diverters-mixers-in-finish/$slug'
    | '/product/$slug'
    | '/showers-in-finish/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BathroomAccessoriesRoute: typeof BathroomAccessoriesRoute
  CareRoute: typeof CareRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FortuneSeriesRoute: typeof FortuneSeriesRoute
  OysterBlackRoute: typeof OysterBlackRoute
  OysterChromeRoute: typeof OysterChromeRoute
  OysterRoseGoldRoute: typeof OysterRoseGoldRoute
  OysterSeriesRoute: typeof OysterSeriesRoute
  ProductsRoute: typeof ProductsRoute
  PyramidSeriesRoute: typeof PyramidSeriesRoute
  SigmaChromeRoute: typeof SigmaChromeRoute
  SigmaGoldRoute: typeof SigmaGoldRoute
  SigmaRoseGoldRoute: typeof SigmaRoseGoldRoute
  SigmaSeriesRoute: typeof SigmaSeriesRoute
  SignatureSeriesRoute: typeof SignatureSeriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolitaireSeriesRoute: typeof SolitaireSeriesRoute
  SupremeChromeRoute: typeof SupremeChromeRoute
  SupremeGoldRoute: typeof SupremeGoldRoute
  SupremeRoseGoldRoute: typeof SupremeRoseGoldRoute
  SwatchChromeRoute: typeof SwatchChromeRoute
  SwatchGoldRoute: typeof SwatchGoldRoute
  SwatchRoseGoldRoute: typeof SwatchRoseGoldRoute
  SwatchSeriesRoute: typeof SwatchSeriesRoute
  UnitySeriesRoute: typeof UnitySeriesRoute
  WarrantyRoute: typeof WarrantyRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DivertersMixersInFinishSlugRoute: typeof DivertersMixersInFinishSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ShowersInFinishSlugRoute: typeof ShowersInFinishSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bathroom-accessories': {
      id: '/bathroom-accessories'
      path: '/bathroom-accessories'
      fullPath: '/bathroom-accessories'
      preLoaderRoute: typeof BathroomAccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fortune-series': {
      id: '/fortune-series'
      path: '/fortune-series'
      fullPath: '/fortune-series'
      preLoaderRoute: typeof FortuneSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyster-black': {
      id: '/oyster-black'
      path: '/oyster-black'
      fullPath: '/oyster-black'
      preLoaderRoute: typeof OysterBlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyster-chrome': {
      id: '/oyster-chrome'
      path: '/oyster-chrome'
      fullPath: '/oyster-chrome'
      preLoaderRoute: typeof OysterChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyster-rose-gold': {
      id: '/oyster-rose-gold'
      path: '/oyster-rose-gold'
      fullPath: '/oyster-rose-gold'
      preLoaderRoute: typeof OysterRoseGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oyster-series': {
      id: '/oyster-series'
      path: '/oyster-series'
      fullPath: '/oyster-series'
      preLoaderRoute: typeof OysterSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyramid-series': {
      id: '/pyramid-series'
      path: '/pyramid-series'
      fullPath: '/pyramid-series'
      preLoaderRoute: typeof PyramidSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma-chrome': {
      id: '/sigma-chrome'
      path: '/sigma-chrome'
      fullPath: '/sigma-chrome'
      preLoaderRoute: typeof SigmaChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma-gold': {
      id: '/sigma-gold'
      path: '/sigma-gold'
      fullPath: '/sigma-gold'
      preLoaderRoute: typeof SigmaGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma-rose-gold': {
      id: '/sigma-rose-gold'
      path: '/sigma-rose-gold'
      fullPath: '/sigma-rose-gold'
      preLoaderRoute: typeof SigmaRoseGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sigma-series': {
      id: '/sigma-series'
      path: '/sigma-series'
      fullPath: '/sigma-series'
      preLoaderRoute: typeof SigmaSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signature-series': {
      id: '/signature-series'
      path: '/signature-series'
      fullPath: '/signature-series'
      preLoaderRoute: typeof SignatureSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solitaire-series': {
      id: '/solitaire-series'
      path: '/solitaire-series'
      fullPath: '/solitaire-series'
      preLoaderRoute: typeof SolitaireSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supreme-chrome': {
      id: '/supreme-chrome'
      path: '/supreme-chrome'
      fullPath: '/supreme-chrome'
      preLoaderRoute: typeof SupremeChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supreme-gold': {
      id: '/supreme-gold'
      path: '/supreme-gold'
      fullPath: '/supreme-gold'
      preLoaderRoute: typeof SupremeGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supreme-rose-gold': {
      id: '/supreme-rose-gold'
      path: '/supreme-rose-gold'
      fullPath: '/supreme-rose-gold'
      preLoaderRoute: typeof SupremeRoseGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swatch-chrome': {
      id: '/swatch-chrome'
      path: '/swatch-chrome'
      fullPath: '/swatch-chrome'
      preLoaderRoute: typeof SwatchChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swatch-gold': {
      id: '/swatch-gold'
      path: '/swatch-gold'
      fullPath: '/swatch-gold'
      preLoaderRoute: typeof SwatchGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swatch-rose-gold': {
      id: '/swatch-rose-gold'
      path: '/swatch-rose-gold'
      fullPath: '/swatch-rose-gold'
      preLoaderRoute: typeof SwatchRoseGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swatch-series': {
      id: '/swatch-series'
      path: '/swatch-series'
      fullPath: '/swatch-series'
      preLoaderRoute: typeof SwatchSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unity-series': {
      id: '/unity-series'
      path: '/unity-series'
      fullPath: '/unity-series'
      preLoaderRoute: typeof UnitySeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diverters-mixers-in-finish/$slug': {
      id: '/diverters-mixers-in-finish/$slug'
      path: '/diverters-mixers-in-finish/$slug'
      fullPath: '/diverters-mixers-in-finish/$slug'
      preLoaderRoute: typeof DivertersMixersInFinishSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showers-in-finish/$slug': {
      id: '/showers-in-finish/$slug'
      path: '/showers-in-finish/$slug'
      fullPath: '/showers-in-finish/$slug'
      preLoaderRoute: typeof ShowersInFinishSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BathroomAccessoriesRoute: BathroomAccessoriesRoute,
  CareRoute: CareRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FortuneSeriesRoute: FortuneSeriesRoute,
  OysterBlackRoute: OysterBlackRoute,
  OysterChromeRoute: OysterChromeRoute,
  OysterRoseGoldRoute: OysterRoseGoldRoute,
  OysterSeriesRoute: OysterSeriesRoute,
  ProductsRoute: ProductsRoute,
  PyramidSeriesRoute: PyramidSeriesRoute,
  SigmaChromeRoute: SigmaChromeRoute,
  SigmaGoldRoute: SigmaGoldRoute,
  SigmaRoseGoldRoute: SigmaRoseGoldRoute,
  SigmaSeriesRoute: SigmaSeriesRoute,
  SignatureSeriesRoute: SignatureSeriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolitaireSeriesRoute: SolitaireSeriesRoute,
  SupremeChromeRoute: SupremeChromeRoute,
  SupremeGoldRoute: SupremeGoldRoute,
  SupremeRoseGoldRoute: SupremeRoseGoldRoute,
  SwatchChromeRoute: SwatchChromeRoute,
  SwatchGoldRoute: SwatchGoldRoute,
  SwatchRoseGoldRoute: SwatchRoseGoldRoute,
  SwatchSeriesRoute: SwatchSeriesRoute,
  UnitySeriesRoute: UnitySeriesRoute,
  WarrantyRoute: WarrantyRoute,
  CategorySlugRoute: CategorySlugRoute,
  DivertersMixersInFinishSlugRoute: DivertersMixersInFinishSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  ShowersInFinishSlugRoute: ShowersInFinishSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
